# -*- coding: utf-8 -*-
"""Contest-kaggle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U8NCMxM1xpp3_v52nYaaXaX000rr44aH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error, log_loss
import operator
import json
from IPython import display
import os
import warnings
 
np.random.seed(0)
warnings.filterwarnings("ignore")
THRESHOLD = 4

from google.colab import drive
drive.mount('/content/drive')

"""Task: To predict whether the user likes the mobile phone or not. <br>
Assumption: If the average rating of mobile >= threshold, then the user likes it, otherwise not.

<b>Missing values:</b><br>
'Also Known As'(459),'Applications'(421),'Audio Features'(437),'Bezel-less display'(266),'Browser'(449),'Build Material'(338),'Co-Processor'(451),'Display Colour'(457),'Mobile High-Definition Link(MHL)'(472),'Music'(447)
'Email','Fingerprint Sensor Position'(174),'Games'(446),'HDMI'(454),'Heart Rate Monitor'(467),'IRIS Scanner'(467),
'Optical Image Stabilisation'(219),'Other Facilities'(444),'Phone Book'(444),'Physical Aperture'(87),'Quick Charging'(122),'Ring Tone'(444),'Ruggedness'(430),SAR Value(315),'SIM 3'(472),'SMS'(470)', 'Screen Protection'(229),'Screen to Body Ratio (claimed by the brand)'(428),'Sensor'(242),'Software Based Aperture'(473),
'Special Features'(459),'Standby time'(334),'Stylus'(473),'TalkTime'(259), 'USB Type-C'(374),'Video Player'(456),
'Video Recording Features'(458),'Waterproof'(398),'Wireless Charging','USB OTG Support'(159), 'Video ,'Recording'(113),'Java'(471),'Browser'(448)

<b>Very low variance:</b><br>
'Architecture'(most entries are 64-bit),'Audio Jack','GPS','Loudspeaker','Network','Network Support','Other Sensors'(28),'SIM Size', 'VoLTE'


<b>Multivalued:</b><br>
'Colours','Custom UI','Model'(1),'Other Sensors','Launch Date'

<b>Not important:</b><br>
'Bluetooth', 'Settings'(75),'Wi-Fi','Wi-Fi Features'

<b>Doubtful:</b><br>
'Aspect Ratio','Autofocus','Brand','Camera Features','Fingerprint Sensor'(very few entries are missing),
'Fingerprint Sensor Position', 'Graphics'(multivalued),'Image resolution'(multivalued),'SIM Size','Sim Slot(s)', 'User Available Storage', 'SIM 1', 'SIM 2','Shooting Modes', 'Touch Screen'(24), 'USB Connectivity'
    
<b>To check:</b><br>
'Display Type','Expandable Memory','FM Radio'

<b>High Correlation with other features</b><br>
'SIM Slot(s)' high correlation with SIM1
'Weight' has high high correlation with capacity , screen-to-body ratio
'Height' - screen size is also there
    
<b>Given a mobile, we can't directly get these features</b><br>
'Rating Count', 'Review Count'

<b>Keeping:</b><br>
'Capacity','Flash'(17),'Height'(22),'Internal Memory'(20, require cleaning),'Operating System'(25, require cleaning), 'Pixel Density'(1, clean it),'Processor'(22, clean it), 'RAM'(17, clean), 'Rating','Resolution'(cleaning), 'Screen Resolution','Screen Size', 'Thickness'(22), 'Type','User Replaceable','Weight'(cleaning),'Sim Size'(), 'Other Sensors'(28), 'Screen to Body Ratio (calculated)','Width',
"""

# read data from file
train = pd.read_csv("/content/drive/MyDrive/kaggle-contest/train.csv") 
test = pd.read_csv("/content/drive/MyDrive/kaggle-contest/test.csv")

# check the number of features and data points in train
print("Number of data points in train: %d" % train.shape[0])
print("Number of features in train: %d" % train.shape[1])

# check the number of features and data points in test
print("Number of data points in test: %d" % test.shape[0])
print("Number of features in test: %d" % test.shape[1])

def data_clean(data):
    
    # Let's first remove all missing value features
    columns_to_remove = ['Also Known As','Applications','Audio Features','Bezel-less display'
                         'Browser','Build Material','Co-Processor','Browser'
                         'Display Colour','Mobile High-Definition Link(MHL)',
                         'Music', 'Email','Fingerprint Sensor Position',
                         'Games','HDMI','Heart Rate Monitor','IRIS Scanner', 
                         'Optical Image Stabilisation','Other Facilities',
                         'Phone Book','Physical Aperture','Quick Charging',
                         'Ring Tone','Ruggedness','SAR Value','SIM 3','SMS',
                         'Screen Protection','Screen to Body Ratio (claimed by the brand)',
                         'Sensor','Software Based Aperture', 'Special Features',
                         'Standby time','Stylus','TalkTime', 'USB Type-C',
                         'Video Player', 'Video Recording Features','Waterproof',
                         'Wireless Charging','USB OTG Support', 'Video Recording','Java']

    columns_to_retain = list(set(data.columns)-set(columns_to_remove))
    data = data[columns_to_retain]

    #Features having very low variance 
    columns_to_remove = ['Architecture','Audio Jack','GPS','Loudspeaker','Network','Network Support','VoLTE']
    columns_to_retain = list(set(data.columns)-set(columns_to_remove))
    data = data[columns_to_retain]

    # Multivalued:
    columns_to_remove = ['Architecture','Launch Date','Audio Jack','GPS','Loudspeaker','Network','Network Support','VoLTE', 'Custom UI']
    columns_to_retain = list(set(data.columns)-set(columns_to_remove))
    data = data[columns_to_retain]

    # Not much important
    columns_to_remove = ['Bluetooth', 'Settings','Wi-Fi','Wi-Fi Features']
    columns_to_retain = list(set(data.columns)-set(columns_to_remove))
    data = data[columns_to_retain]
    
    return data

"""# Removing features"""

train = data_clean(train)
test = data_clean(test)

"""removing all those data points in which more than 15 features are missing """

train = train[(train.isnull().sum(axis=1) <= 15)]
# You shouldn't remove data points from test set
#test = test[(test.isnull().sum(axis=1) <= 15)]

# check the number of features and data points in train
print("Number of data points in train: %d" % train.shape[0])
print("Number of features in train: %d" % train.shape[1])

# check the number of features and data points in test
print("Number of data points in test: %d" % test.shape[0])
print("Number of features in test: %d" % test.shape[1])

"""# Filling Missing values"""

def for_integer(test):
    try:
        test = test.strip()
        return int(test.split(' ')[0])
    except IOError:
           pass
    except ValueError:
        pass
    except:
        pass

def for_string(test):
    try:
        test = test.strip()
        return (test.split(' ')[0])
    except IOError:
        pass
    except ValueError:
        pass
    except:
        pass

def for_float(test):
    try:
        test = test.strip()
        return float(test.split(' ')[0])
    except IOError:
        pass
    except ValueError:
        pass
    except:
        pass
def find_freq(test):
    try:
        test = test.strip()
        test = test.split(' ')
        if test[2][0] == '(':
            return float(test[2][1:])
        return float(test[2])
    except IOError:
        pass
    except ValueError:
        pass
    except:
        pass

    
def for_Internal_Memory(test):
    try:
        test = test.strip()
        test = test.split(' ')
        if test[1] == 'GB':
            return int(test[0])
        if test[1] == 'MB':
#             print("here")
            return (int(test[0]) * 0.001)
    except IOError:
           pass
    except ValueError:
        pass
    except:
        pass
    
def find_freq(test):
    try:
        test = test.strip()
        test = test.split(' ')
        if test[2][0] == '(':
            return float(test[2][1:])
        return float(test[2])
    except IOError:
        pass
    except ValueError:
        pass
    except:
        pass

def data_clean_2(x):
    data = x.copy()
    
    data['Capacity'] = data['Capacity'].apply(for_integer)

    data['Height'] = data['Height'].apply(for_float)
    data['Height'] = data['Height'].fillna(data['Height'].mean())

    data['Internal Memory'] = data['Internal Memory'].apply(for_Internal_Memory)

    data['Pixel Density'] = data['Pixel Density'].apply(for_integer)

    data['Internal Memory'] = data['Internal Memory'].fillna(data['Internal Memory'].median())
    data['Internal Memory'] = data['Internal Memory'].astype(int)

    data['RAM'] = data['RAM'].apply(for_integer)
    data['RAM'] = data['RAM'].fillna(data['RAM'].median())
    data['RAM'] = data['RAM'].astype(int)

    data['Resolution'] = data['Resolution'].apply(for_integer)
    data['Resolution'] = data['Resolution'].fillna(data['Resolution'].median())
    data['Resolution'] = data['Resolution'].astype(int)

    data['Screen Size'] = data['Screen Size'].apply(for_float)

    data['Thickness'] = data['Thickness'].apply(for_float)
    data['Thickness'] = data['Thickness'].fillna(data['Thickness'].mean())
    data['Thickness'] = data['Thickness'].round(2)

    data['Type'] = data['Type'].fillna('Li-Polymer')

    data['Screen to Body Ratio (calculated)'] = data['Screen to Body Ratio (calculated)'].apply(for_float)
    data['Screen to Body Ratio (calculated)'] = data['Screen to Body Ratio (calculated)'].fillna(data['Screen to Body Ratio (calculated)'].mean())
    data['Screen to Body Ratio (calculated)'] = data['Screen to Body Ratio (calculated)'].round(2)

    data['Width'] = data['Width'].apply(for_float)
    data['Width'] = data['Width'].fillna(data['Width'].mean())
    data['Width'] = data['Width'].round(2)

    data['Flash'][data['Flash'].isna() == True] = "Other"

    data['User Replaceable'][data['User Replaceable'].isna() == True] = "Other"

    data['Num_cores'] = data['Processor'].apply(for_string)
    data['Num_cores'][data['Num_cores'].isna() == True] = "Other"


    data['Processor_frequency'] = data['Processor'].apply(find_freq)
    #because there is one entry with 208MHz values, to convert it to GHz
    data['Processor_frequency'][data['Processor_frequency'] > 200] = 0.208
    data['Processor_frequency'] = data['Processor_frequency'].fillna(data['Processor_frequency'].mean())
    data['Processor_frequency'] = data['Processor_frequency'].round(2)

    data['Camera Features'][data['Camera Features'].isna() == True] = "Other"

    #simplifyig Operating System to os_name for simplicity
    data['os_name'] = data['Operating System'].apply(for_string)
    data['os_name'][data['os_name'].isna() == True] = "Other"

    data['Sim1'] = data['SIM 1'].apply(for_string)

    data['SIM Size'][data['SIM Size'].isna() == True] = "Other"

    data['Image Resolution'][data['Image Resolution'].isna() == True] = "Other"

    data['Fingerprint Sensor'][data['Fingerprint Sensor'].isna() == True] = "Other"

    data['Expandable Memory'][data['Expandable Memory'].isna() == True] = "No"

    data['Weight'] = data['Weight'].apply(for_integer)
    data['Weight'] = data['Weight'].fillna(data['Weight'].mean())
    data['Weight'] = data['Weight'].astype(int)

    data['SIM 2'] = data['SIM 2'].apply(for_string)
    data['SIM 2'][data['SIM 2'].isna() == True] = "Other"
    
    return data

train = data_clean_2(train)
test = data_clean_2(test)

# check the number of features and data points in train
print("Number of data points in train: %d" % train.shape[0])
print("Number of features in train: %d" % train.shape[1])

# check the number of features and data points in test
print("Number of data points in test: %d" % test.shape[0])
print("Number of features in test: %d" % test.shape[1])

"""Not very important feature"""

def data_clean_3(x):
    
    data = x.copy()

    columns_to_remove = ['User Available Storage','SIM Size','Chipset','Processor','Autofocus','Aspect Ratio','Touch Screen',
                        'Bezel-less display','Operating System','SIM 1','USB Connectivity','Other Sensors','Graphics','FM Radio',
                        'NFC','Shooting Modes','Browser','Display Colour' ]

    columns_to_retain = list(set(data.columns)-set(columns_to_remove))
    data = data[columns_to_retain]


    columns_to_remove = [ 'Screen Resolution','User Replaceable','Camera Features',
                        'Thickness', 'Display Type']

    columns_to_retain = list(set(data.columns)-set(columns_to_remove))
    data = data[columns_to_retain]


    columns_to_remove = ['Fingerprint Sensor', 'Flash', 'Rating Count', 'Review Count','Image Resolution','Type','Expandable Memory',\
                        'Colours','Width','Model']
    columns_to_retain = list(set(data.columns)-set(columns_to_remove))
    data = data[columns_to_retain]

    return data

train = data_clean_3(train)
test = data_clean_3(test)

# check the number of features and data points in train
print("Number of data points in train: %d" % train.shape[0])
print("Number of features in train: %d" % train.shape[1])

# check the number of features and data points in test
print("Number of data points in test: %d" % test.shape[0])
print("Number of features in test: %d" % test.shape[1])

# one hot encoding

train_ids = train['PhoneId']
test_ids = test['PhoneId']

cols = list(test.columns)
cols.remove('PhoneId')
cols.insert(0, 'PhoneId')

combined = pd.concat([train.drop('Rating', axis=1)[cols], test[cols]])
print(combined.shape)
print(combined.columns)

combined = pd.get_dummies(combined)
print(combined.shape)
print(combined.columns)

train_new = combined[combined['PhoneId'].isin(train_ids)]
test_new = combined[combined['PhoneId'].isin(test_ids)]

train_new = train_new.merge(train[['PhoneId', 'Rating']], on='PhoneId')

# check the number of features and data points in train
print("Number of data points in train: %d" % train_new.shape[0])
print("Number of features in train: %d" % train_new.shape[1])

# check the number of features and data points in test
print("Number of data points in test: %d" % test_new.shape[0])
print("Number of features in test: %d" % test_new.shape[1])

train_new.head()

test_new.head()

"""## Dummy Solution"""

# submission = pd.DataFrame({'PhoneId':test_new['PhoneId'], 'Class':[0]*test_new.shape[0]})
# submission = submission[['PhoneId', 'Class']]
# submission.head()

# submission.to_csv("submission.csv", index=False)

Y_train = train_new['Rating']
X_train = train_new
X_test = test_new

Y_train_binary = []
for x in Y_train:
  if x >= 4 :
    Y_train_binary.append(1)
  elif x < 4:
    Y_train_binary.append(0)
Y_train_binary = pd.DataFrame(Y_train_binary,columns=['Rating'])

X_train.drop(['Rating'], axis=1, inplace=True)
X_train.drop(['PhoneId'], axis=1, inplace=True)

X_train.head()

X_train["Pixel Density"] = (X_train["Pixel Density"] - X_train["Pixel Density"].min()) / (X_train["Pixel Density"].max() - X_train["Pixel Density"].min())
X_train["Weight"] = (X_train["Weight"] - X_train["Weight"].min()) / (X_train["Weight"].max() - X_train["Weight"].min())
X_train["Processor_frequency"] = (X_train["Processor_frequency"] - X_train["Processor_frequency"].min()) / (X_train["Processor_frequency"].max() - X_train["Processor_frequency"].min())
X_train["RAM"] = (X_train["RAM"] - X_train["RAM"].min()) / (X_train["RAM"].max() - X_train["RAM"].min())
X_train["Screen to Body Ratio (calculated)"] = (X_train["Screen to Body Ratio (calculated)"] - X_train["Screen to Body Ratio (calculated)"].min()) / (X_train["Screen to Body Ratio (calculated)"].max() - X_train["Screen to Body Ratio (calculated)"].min())
X_train["Capacity"] = (X_train["Capacity"] - X_train["Capacity"].min()) / (X_train["Capacity"].max() - X_train["Capacity"].min())
X_train["Height"] = (X_train["Height"] - X_train["Height"].min()) / (X_train["Height"].max() - X_train["Height"].min())
X_train["Internal Memory"] = (X_train["Internal Memory"] - X_train["Internal Memory"].min()) / (X_train["Internal Memory"].max() - X_train["Internal Memory"].min())
X_train["Screen Size"] = (X_train["Screen Size"] - X_train["Screen Size"].min()) / (X_train["Screen Size"].max() - X_train["Screen Size"].min())
X_train["Resolution"] = (X_train["Resolution"] - X_train["Resolution"].min()) / (X_train["Resolution"].max() - X_train["Resolution"].min())

X_test["Pixel Density"] = (X_test["Pixel Density"] - X_test["Pixel Density"].min()) / (X_test["Pixel Density"].max() - X_test["Pixel Density"].min())
X_test["Weight"] = (X_test["Weight"] - X_test["Weight"].min()) / (X_test["Weight"].max() - X_test["Weight"].min())
X_test["Processor_frequency"] = (X_test["Processor_frequency"] - X_test["Processor_frequency"].min()) / (X_test["Processor_frequency"].max() - X_test["Processor_frequency"].min())
X_test["RAM"] = (X_test["RAM"] - X_test["RAM"].min()) / (X_test["RAM"].max() - X_test["RAM"].min())
X_test["Screen to Body Ratio (calculated)"] = (X_test["Screen to Body Ratio (calculated)"] - X_test["Screen to Body Ratio (calculated)"].min()) / (X_test["Screen to Body Ratio (calculated)"].max() - X_test["Screen to Body Ratio (calculated)"].min())
X_test["Capacity"] = (X_test["Capacity"] - X_test["Capacity"].min()) / (X_test["Capacity"].max() - X_test["Capacity"].min())
X_test["Height"] = (X_test["Height"] - X_test["Height"].min()) / (X_test["Height"].max() - X_test["Height"].min())
X_test["Internal Memory"] = (X_test["Internal Memory"] - X_test["Internal Memory"].min()) / (X_test["Internal Memory"].max() - X_test["Internal Memory"].min())
X_test["Screen Size"] = (X_test["Screen Size"] - X_test["Screen Size"].min()) / (X_test["Screen Size"].max() - X_test["Screen Size"].min())
X_test["Resolution"] = (X_test["Resolution"] - X_test["Resolution"].min()) / (X_test["Resolution"].max() - X_test["Resolution"].min())

X_train.head()

Y_train_binary.head()
print(Y_train_binary)

class Perceptron:
  def __init__ (self):
    self.w = None
    self.b = None
 
  def model(self, x):
    return 1 if (np.dot(self.w, x) + self.b >= self.b) else 0
 
  def predict(self, X):
    Y = []
    for x in X:
      result = self.model(x)
      Y.append(result)
    return np.array(Y)
 
  def fit(self, X, Y, epoc, learning_rate = 1):
    self.w = np.ones(X.shape[1])
    self.b = 0
    accuracy = []
    max_accuracy = 0
    max_accuracy_point = 0
 
    for i in range(epoc):
      for x, y in zip(X, Y):
        y_pred = self.model(x)
        if y == 1 and y_pred == 0:
          self.w = self.w + learning_rate * x
          self.b = self.b + learning_rate * 1
        elif y == 0 and y_pred == 1:
          self.w = self.w - learning_rate * x
          self.b = self.b - learning_rate * 1
      accuracy.append(accuracy_score(self.predict(X),  Y))
      if (accuracy[i] > max_accuracy):
        max_accuracy = accuracy[i]
        max_accuracy_point = i
        checkw = self.w
        checkb = self.b
 
    self.w = checkw
    self.b = checkb
    plt.plot(accuracy)
    plt.show()
    print("Max accuracy = ",max_accuracy)
    print("Max accuracy point = ",max_accuracy_point)
 
 
perceptron = Perceptron()

x_train = X_train.values
y_train = Y_train_binary.values
X_test.drop(['PhoneId'], axis=1, inplace=True)
x_test = X_test.values
# print(x_train)
# print(y_train)

perceptron.fit(x_train, y_train, 10000, 0.001)

from sklearn.metrics import accuracy_score

Y_pred = perceptron.predict(x_train)
print("Train ",accuracy_score(Y_pred, Y_train_binary)) 

Y_test_pred = perceptron.predict(x_test)
# print("Train ",accuracy_score(Y_test, Y_train_binary))
print(Y_test_pred)

submission = pd.DataFrame({'PhoneId':demtest['PhoneId'], 'Class': Y_pred_test})
submission = submission[['PhoneId', 'Class']]
submission.head()

submission.to_csv("submission.csv", index=False)